### ISSUE TITLE
Give mobs temporary invulnerability when they rise from the ground

### ISSUE THREAD

**Issue by Fishvap** [Tschipcraft/spawnanimations#1]
### Is your suggested enhancement related to a problem? Please describe.

I'm not certain if it's already a feature since I haven't used this yet, however since the screenshots indicate otherwise I will drop the issue anyway.

### Describe the solution you'd like

Mobs should be given temporary invulnerability when spawned so that they won't suffocate in blocks, until they are at least halfway through the animation.

**Comment by Tschipcraft** [comment]
The mobs already get the resistance effect while digging out, so they are not loosing any health. They will however still flash red, what could be prevented with your approach. 
Thank you for your idea, I will incorporate it in the next release!
