### ISSUE TITLE
Đỏ màn hình

### ISSUE THREAD

**Issue by Bi-G000** [Tschipcraft/spawnanimations#13]
### Describe the bug

![image](https://github.com/Tschipcraft/spawnanimations/assets/76668749/a24220c3-1693-4772-bc27-003f1b56afa9)

Không thể nào hết hiệu ứng đỏ màn hình

### Steps to reproduce

1. Chạy thử cả 3 chế độ
2. Lỗi viền đỏ không hết

### Expected behavior

Sửa lỗi

### Additional context

Xin cảm ơn !

**Comment by Tschipcraft** [comment]
Đây không phải là vấn đề với Spawn Animations. Tôi không sửa đổi tia sáng đỏ đến từ biên giới thế giới theo bất kỳ cách nào.
Tuy nhiên, bạn có thể thử chạy lệnh `/worldborder warning distance 5`.

Ồ và vui lòng sử dụng tiếng Anh cho các vấn đề hoặc nhận xét khác.

<sup>Thư này đã được dịch bằng Google Dịch và có thể chứa lỗi.</sup>

<details>
<summary>Translation for anyone interested</summary>

Issue: Redscreen
>### Describe the Bug:
>Can't get rid of the red screen effect
>### Steps to repruduce:
>1. Test run all 3 modes
>2. The error of the red border does not go away
>### Expected behavior:
>Fix the error

My comment:
>This is not an issue with Spawn Animations. I do not modify the red glint that comes from the worldborder in any way.
>However, you could try running the command `/worldborder warning distance 5`.
>
>Oh and please stick with english for further issues or comments.
</details>
