### ISSUE TITLE
Global settings across all worlds

### ISSUE THREAD

**Issue by Xliecc** [Tschipcraft/spawnanimations#15]
Can my settings in the menu be saved to every world？it's a bit of a hassle for me to enter commands every time I enter a new world

**Comment by Tschipcraft** [comment]
This is currently not possible without editing the data pack itself and changing the default values in the install function located in _/data/spawnanimations/functions/install.mcfunction_.

I am however working on a global settings menu for the mod version of this data pack that implements exactly that. I will slowly roll out this feature for my data packs starting with More Mobs in the next weeks.

**Comment by Tschipcraft** [comment]
This feature is now available in v1.9.2 🎉
