### ISSUE TITLE
Charged creeper glow is not hidden

### ISSUE THREAD

**Issue by peow** [Tschipcraft/spawnanimations#17]
### Describe the bug

I'm using the mod for fabric 1.20.1, and along with it I'm using a mod that makes Charged Creepers spawn naturally, but when they spawn, their glow is above the ground, making it possible to see from a distance

![2023-11-07_22 12 04](https://github.com/Tschipcraft/spawnanimations/assets/105888751/0e547471-7e94-473e-95dc-1537a99feca9)

![2023-11-07_22 12 16](https://github.com/Tschipcraft/spawnanimations/assets/105888751/16145e8f-3c71-4ff1-b02d-41f4fdaf87f7)

### Steps to reproduce

1. get the coordinates to summon a charged creeper
2. go very far, like 50 blocks
3. use the command /summon minecraft:creeper (coordinates) {powered:1b}

### Expected behavior

the charged creeper's glow be hidden under the ground

### Additional context

pls make an update to fabric 1.20.1

**Comment by Tschipcraft** [comment]
Thank you for the bug report, this will be fixed in a future update!

**Comment by Tschipcraft** [comment]
This has been fixed in v1.9.3 🎉

**Comment by Tschipcraft** [comment]
Thank you, but this seems to be an issue with, I assume, Fresh Animations and doesn't occur in Minecraft vanilla.
Since this project is just a data pack at its core, I can only hide the entities by giving them invisibility or turn off e.g. the creeper glow using nbt modifications.
