### ISSUE TITLE
Small conflict with More Mobs

### ISSUE THREAD

**Issue by Goober19** [Tschipcraft/spawnanimations#2]
### Describe the bug

The More Mobs mod just adds variants to all of the vanilla mobs to spice up gameplay, however with Spawn animations you can tell where mobs are going to spawn because their custom heads and weapons will float around til they spawn in

### Steps to reproduce

1. Install More Mobs and Spawn Animations
2. Run around at night, see floating heads
3. upon getting close, the floating head will disappear and the mob will rise intentionally

### Expected behavior

For mobs held weapons and custom heads to also be invisible until they surface

**Comment by Tschipcraft** [comment]
Interesting, I thought I had a system in place for compatibility between Spawn Animations and More Mobs. Seems like it doesn't work...
Will be fixed in next release 👍
