### ISSUE TITLE
From a distance, part of the mobs aren't invisible

### ISSUE THREAD

**Issue by retropele** [Tschipcraft/spawnanimations#3]
### Describe the bug

Before the spawning animation starts (at a particular distance) emissive textures like spider eyes and endermen eyes if enabled just float around and can be seen moving, as well as Endermen's block if they are carrying one.

The same goes for armour worn by zombies/skeletons which you can see empty with no mob inside before the animation starts.

Any solutions, or just unfixable? I love this.

### Steps to reproduce

1. Play with emissive textures on.
2. Go outside and wait until enemy spawns.
3. Observe visible eyes, held items/blocks and worn armour walking around.
4. Get close and see these disappear for a moment as the mob spawns below ground.

### Expected behavior

Mobs to be fully invisible before they spawn in.

### Additional context

I know this may be due to an incongruent mob spawning distance vs spawning animation distance, however I don't know where to find a spawning animation distance toggle.

**Comment by Tschipcraft** [comment]
This is a known annoyance. 
Right now, the data pack is designed to be as unintrusive as possible to other mods that may alter spawning rates and check for any mobs and their worn loot nearby. So the mobs that have not played their animation yet, stay where they are with the loot they've been given. 
Sadly, I can't hide the worn armor/held tools and any emissive parts of an entity with the invisibility effect.

One possible solution for armor and tools could be storing them somewhere else in the entity (maybe in a container with nbt in a slot that doesn't render (e.g. the feet slot)).
The other option would be to literally hide the mobs under the ground, but then they will not be able to move and interact with farms, for example.

I will most likely add an option for one of the possible solution in the future (as well as an animation distance slider).

**Comment by retropele** [comment]
Thanks so much for answering me. I see I'm asking for an enhancement then instead! 

I don't run farms, so having it being a toggle would be great someday (though again I know there could be big issues with just shoving a bunch of mobs underground all the time), and the slider sounds ideal, because what I would probably personally do is just make it so the animation distance is closer to my entity spawn distance, even if that meant I rarely see the animation - it's very scary and immersive and weird.

One of the best mods I've used in ages and really surprisingly low impact, so thanks so much for it!! I'll try and change the tag on this to "enhancement" but if not, you're welcome to change it if you can.

Thank you for the cool mod!!
