### ISSUE TITLE
[Question]: Custom Particles?

### ISSUE THREAD

**Issue by Fyoncle** [Tschipcraft/spawnanimations#30]
### What is your question? Please describe.

![image](https://github.com/user-attachments/assets/0701a012-ae5d-47de-8c22-3049de913049)
![image](https://github.com/user-attachments/assets/bdfcd76e-6f36-42cc-ae4c-f888b175c66d)
Can i edit these and add modded mobs just like i can in dig up and poof animations?

**Comment by Tschipcraft** [comment]
Yes

**Comment by Fyoncle** [comment]
> Yes

Like that? ;)
![image](https://github.com/user-attachments/assets/7634c46a-2900-4832-a04d-1650e7796b21)
![image](https://github.com/user-attachments/assets/9ef6db47-f8c0-4c9d-8f08-4fc6257ff2b7)
![image](https://github.com/user-attachments/assets/d68cc139-8e15-4c26-aad4-54e7ada14131)
![image](https://github.com/user-attachments/assets/f5f441fb-59e8-44d7-88e7-1ed84d7a0242)

I add it via my mod so i won't have to edit the files of ur mod every time i take update.

**Comment by Fyoncle** [comment]
Well it didn't work.
I don't know what i did wrong ;v
![image](https://github.com/user-attachments/assets/da1d4daa-2018-4849-b14c-a9beabf86849)

**Comment by Tschipcraft** [comment]
I don't know, everything looks correct... Could you check your logs for any errors?

**Comment by Fyoncle** [comment]
![image](https://github.com/user-attachments/assets/301f7823-11ee-4b22-9563-c8309a06824b)
Oh? i think i did a mistake

**Comment by Fyoncle** [comment]
![image](https://github.com/user-attachments/assets/7846842b-f470-45db-b3a1-68d6f2c83160)
But i did everything right :(

**Comment by Fyoncle** [comment]
Oh nvm everything alright, it was my bad. I forgot theres a older version of Deeper And Darker in my test version.

**Comment by Tschipcraft** [comment]
Added this info to the wiki, unpinning now
