### ISSUE TITLE
Update to Fabric 1.21 please

### ISSUE THREAD

**Issue by GodReza** [Tschipcraft/spawnanimations#31]
Please update to 1.21

**Comment by Tschipcraft** [comment]
I'm working on it, see #28

**Comment by Fyoncle** [comment]
Can we get 1.21.1 too? :)

**Comment by Tschipcraft** [comment]
Yes, the next release will add support for 1.20.5–1.21.4

**Comment by Fyoncle** [comment]
> Yes, the next release will add support for 1.20.5–1.21.4

❤️ You're awesome!
