### ISSUE TITLE
This datapack will go wrong when there are other datapack

### ISSUE THREAD

**Issue by Dr-WeiAL** [Tschipcraft/spawnanimations#4]
### Describe the bug

I used openloader, which loaded some packets, I found in the course of the game, the monster out of the ground animation disappeared, looking at the monster invisible, and then after a few seconds suddenly appeared

But when I removed all the data packets temporarily, the monster emergence animation returned to normal after entering the game, and even if the removed data packets are added back, the emergence animation is still normal

### Steps to reproduce

1.Install this and other data datapack
2.No monster out of the ground animation
3.Remove other datapack
4.Monster out of the ground animation normal
5.Adding back the removed datapack
6.Monster out of the ground animation normal

### Expected behavior

Make it display the monster out animation properly?

### Additional context

Very unstable, I do not know how it appeared or how to fix it, but the steps are this

**Comment by Tschipcraft** [comment]
Thank you for the bug report!
What were the other data pack(s) that you installed using openloader alongside Spawn Animations?

**Comment by Dr-WeiAL** [comment]
Should be what the data package will appear this problem, my side is to install a few simple data package I wrote myself, which only modified the recipe of certain mod, as well as better combat weapon data

**Comment by Tschipcraft** [comment]
I see, if the other data packs only modify recipes and mod data, they are not contributing to the issue.
Did it break midway through, or did it just not play the animation correctly from the beginning?

**Comment by Tschipcraft** [comment]
@Dr-WeiAL does this issue still persist in the latest release v1.9?

**Comment by Dr-WeiAL** [comment]
Oh sure, I haven't closed the game
[latest.log](https://github.com/Tschipcraft/spawnanimations/files/11501104/latest.log)

**Comment by Tschipcraft** [comment]
I think the warning just triggered because the data pack was installed using the command. If you see it again, run this command `/function spawnanimations:settings/disable_hidearmorandtools`. This will deactivate the hiding of armor and tools.

If you don't experience any other issues with the other two mods, you can leave Savage and Ravage installed, it's really just the installation trigger that got messed up (Needs to only run once per world)

**Comment by Tschipcraft** [comment]
Alright, glad it's working now
