### ISSUE TITLE
Entities having the glowing effect applied upon spawning continue glowing when hidden

### ISSUE THREAD

**Issue by Dr-WeiAL** [Tschipcraft/spawnanimations#5]
### Describe the bug

Apotheosis will randomly generate some monsters with prefix items in the vicinity, these monsters are not hidden when they are generated, and will suddenly burrow into the ground and come out again when the player is close to the monster

### Steps to reproduce

1. Using Apotheosis
2. Casually stroll around waiting to generate monsters
3. Approach the monster

### Expected behavior

I don't know, because it glows when it is generated

### Additional context

![image](https://user-images.githubusercontent.com/47446553/232135921-ffcbdb01-68f9-4341-8619-832179aaedb0.png)
![image](https://user-images.githubusercontent.com/47446553/232135951-9520f0be-cb97-4414-a30f-0bb6dac01e06.png)

**Comment by Tschipcraft** [comment]
I see, this may be fixable by storing the glowing effect somewhere else or by checking if the entity has a glowing effect before applying the invisibility phase.
Thank you for the report!

**Comment by Dr-WeiAL** [comment]
Uh, although it seems to be different from what I want to express, but it is indeed a problem
What I was going to say was that looking at the monsters from a distance, they were invisible, but the weapon armor wasn't hidden, and then also included the spider's eyes

**Comment by Tschipcraft** [comment]
Oh I see, this was already reported in #3. I hadn't thought about the glowing potion effect though.
